// (c) 2026 Nakul Mundhada. All rights reserved.


export const ExtensionState = Object.freeze({
  INITIALIZING: 'INITIALIZING',
  WAITING_FOR_PORTAL: 'WAITING_FOR_PORTAL',
  SCHEDULE_DETECTED: 'SCHEDULE_DETECTED',
  ATTENDANCE_DETECTED: 'ATTENDANCE_DETECTED',
  MATCHING: 'MATCHING',
  READY: 'READY',
  STALE_DATA: 'STALE_DATA',
  MATCH_ERROR: 'MATCH_ERROR',
  PARSER_ERROR: 'PARSER_ERROR',
});

export const PageType = Object.freeze({
  STUDENT_HOME: 'student-home',
  ATTENDANCE: 'attendance',
  TIMETABLE: 'timetable',
  UNKNOWN: 'unknown',
});

export const RecommendationType = Object.freeze({
  MUST_ATTEND: 'MUST_ATTEND',
  ATTEND_LOW_BUFFER: 'ATTEND_LOW_BUFFER',
  BUNK_SAFE: 'BUNK_SAFE',
  OPTIONAL: 'OPTIONAL',
  DATA_NOT_VERIFIED: 'DATA_NOT_VERIFIED',
  HIGH_RISK: 'HIGH_RISK',
});

export const RiskLevel = Object.freeze({
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  SAFE: 'SAFE',
});

export const MatchMethod = Object.freeze({
  COURSE_CODE_EXACT: 'COURSE_CODE_EXACT',
  COURSE_CODE_PARTIAL: 'COURSE_CODE_PARTIAL',
  NAME_EXACT: 'NAME_EXACT',
  NAME_FUZZY: 'NAME_FUZZY',
  USER_ALIAS: 'USER_ALIAS',
  PORTAL_ID: 'PORTAL_ID',
  UNMATCHED: 'UNMATCHED',
});

export const MessageType = Object.freeze({

  SCHEDULE_PARSED: 'SCHEDULE_PARSED',
  ATTENDANCE_PARSED: 'ATTENDANCE_PARSED',
  TIMETABLE_PARSED: 'TIMETABLE_PARSED',
  CALENDAR_PARSED: 'CALENDAR_PARSED',
  PAGE_DETECTED: 'PAGE_DETECTED',
  FACULTY_PARSED: 'FACULTY_PARSED',
  STUDENT_INFO_PARSED: 'STUDENT_INFO_PARSED',

  INJECT_RECOMMENDATIONS: 'INJECT_RECOMMENDATIONS',
  INJECT_ATTENDANCE_ENHANCEMENTS: 'INJECT_ATTENDANCE_ENHANCEMENTS',

  GET_TODAY_PLAN: 'GET_TODAY_PLAN',
  GET_STATE: 'GET_STATE',
  GET_SUBJECTS: 'GET_SUBJECTS',
  GET_HOLIDAYS: 'GET_HOLIDAYS',
  GET_DEBUG_INFO: 'GET_DEBUG_INFO',
  GET_PREFERENCES: 'GET_PREFERENCES',
  SAVE_PREFERENCES: 'SAVE_PREFERENCES',
  FORCE_RESYNC: 'FORCE_RESYNC',
  EXPORT_DATA: 'EXPORT_DATA',
  CLEAR_DATA: 'CLEAR_DATA',
  SAVE_ALIAS: 'SAVE_ALIAS',
  GET_WHAT_IF: 'GET_WHAT_IF',
  GET_PROJECTIONS: 'GET_PROJECTIONS',
  GET_STUDENT_INFO: 'GET_STUDENT_INFO',
  OPEN_OPTIONS: 'OPEN_OPTIONS',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  RESET_SESSION: 'RESET_SESSION',
});

export const DEFAULT_PREFERENCES = Object.freeze({
  subjectTarget: 60,
  overallTarget: 75,
  safetyBuffer: 2,
  preferredBunkDays: [],
  semesterEndDate: null,
  portalDomain: 'rcoem.in',
  aliasMap: {},
  debugMode: false,
  staleDataThresholdHours: 48,
  firstRunComplete: false,
});
